# Model config
image_size: 50
model_name: RPS-ISO

# Training config
epochs: 100

# Data config
data_raw_path: "data/raw"
data_interim_path: "data/interim"
data_processed_path: "data/processed"

data_labels:
  0: RPS
  1: ISO

data_files:
  - file: "A.r.m1.dir.tar.gz"
    data_set_type: categorical
    label_start: 0
  - file: "A.i.m1.dir.tar.gz"
    data_set_type: categorical
    label_start: 1

# Model training configuration
data_train_split: 0.8
data_validation_split: 0.8
data_batch_size: 32
data_num_classes: 2

model_directory: "models"
