# Model config
image_size: 50

# Training config
epochs: 1000
enable_tensorboard: True
enable_earlystopping: False

# Data config
data_raw_path: "data/raw"
data_interim_path: "data/interim"
data_processed_path: "data/processed"

data_labels:
  0: TID
  1: RPS
  2: ISO

# mass distrubution and star distribution
data_files:
  # Tidal inteaction data
  - file_1: "A.ts.m1.dir.tar.gz"
    file_2: "A.ts.m1v.dir.tar.gz"
    data_set_type: categorical_2_channel
    label_start: 0
  - file_1: "A.ts.m2.dir.tar.gz"
    file_2: "A.ts.m2v.dir.tar.gz"
    data_set_type: categorical_2_channel
    label_start: 0
  - file_1: "A.ts.m3.dir.tar.gz"
    file_2: "A.ts.m3v.dir.tar.gz"
    data_set_type: categorical_2_channel
    label_start: 0
  # Ram pressure stripping data
  - file_1: "A.rs.m1.dir.tar.gz"
    file_2: "A.rs.m1v.dir.tar.gz"
    data_set_type: categorical_2_channel
    label_start: 1
  - file_1: "A.rs.m2.dir.tar.gz"
    file_2: "A.rs.m2v.dir.tar.gz"
    data_set_type: categorical_2_channel
    label_start: 1
  - file_1: "A.rs.m3.dir.tar.gz"
    file_2: "A.rs.m3v.dir.tar.gz"
    data_set_type: categorical_2_channel
    label_start: 1
  # Isolated data
  - file_1: "A.is.m1.dir.tar.gz"
    file_2: "A.is.m1v.dir.tar.gz"
    data_set_type: categorical_2_channel
    label_start: 2
  - file_1: "A.is.m2.dir.tar.gz"
    file_2: "A.is.m2v.dir.tar.gz"
    data_set_type: categorical_2_channel
    label_start: 2
  - file_1: "A.is.m3.dir.tar.gz"
    file_2: "A.is.m3v.dir.tar.gz"
    data_set_type: categorical_2_channel
    label_start: 2
  
# Model training configuration
data_train_split: 0.8
data_validation_split: 0.8
data_batch_size: 32
data_num_classes: 3

model_type: 2_channel
model_directory: models
model_name: 2_channel_star_star_v_m1_m2_m3

log_dir: "logs/fit"
