# Model config
image_size: 50

# Training config
epochs: 100

# Data config
data_sets:
  week1_data_train:
    data_files:
      - file: "../data/A.m1.dir.tar.gz"
        label_file_name: "m1.dir/2dftn1.dat"
        labels: {0: 0}
        default_label: 1
      
      - file: "../data/A.i.m1.dir.tar.gz"
        label_file_name: "m1.dir/2dftn1.dat"
        default_label: 2

data_train_split: 0.8
data_validation_split: 0.8
data_batch_size: 32
data_num_classes: 3
