# Model config
image_size: 50

# Training config
epochs: 100
enable_tensorboard: True
enable_earlystopping: False

# Data config
data_raw_path: "data/raw"
data_interim_path: "data/interim"
data_processed_path: "data/processed"

data_labels:
  0: TID
  1: RPS
  2: ISO

data_files:
  - file_1: "A.t.m1.dir.tar.gz"
    file_2: "A.ts.m1.dir.tar.gz"
    data_set_type: categorical_2_channel
    label_start: 0
  - file_1: "A.r.m1.dir.tar.gz"
    file_2: "A.rs.m1.dir.tar.gz"
    data_set_type: categorical_2_channel
    label_start: 1
  - file_1: "A.i.m1.dir.tar.gz"
    file_2: "A.is.m1.dir.tar.gz"
    data_set_type: categorical_2_channel
    label_start: 2
  
# Model training configuration
data_train_split: 0.8
data_validation_split: 0.8
data_batch_size: 32
data_num_classes: 3

model_type: "2_channel"
model_directory: "models"
model_name: 2-Model

log_dir: "logs/fit"
