# Model config
image_size: 50

# Training config
epochs: 100

# Data config
data_sets:
  week1_data_train:
    image_data: ["../data/Week1/2dft.dat", "../data/Week1/2dft.i.dat"]
    label_data: "../data/Week1/2dftn.dat"

data_train_split: 0.8
data_validation_split: 0.8
data_batch_size: 32
data_num_classes: 3
