# Model config
image_size: 50

# Training config
epochs: 10

# Data config
data_sets:
  week0_data_training:
    image_data: "../data/2dft.dat"
    label_data_RAM: "../data/2dftn1.dat"
    label_data_TID: "../data/2dftn2.dat"
    image_size: 50

data_train_split: 0.8
data_batch_size: 32